### ISSUE TITLE
Compatibility for TYPO3 7.6

### ISSUE THREAD

**Issue by arunc43** [astehlik/typo3-extension-formhandler_subscription#18]
Hi,

Do you've a plan to fixing the compatibility of this extension with Typo3 7.6 LTS? I saw that formhandler new version is compatible with Typo3 7.6. But your extension is not compatible now.

Expecting your feedback!

Thanks,
Arun

**Comment by astehlik** [comment]
Hi Arun,

thank you for your request.  I updated the current master and it should now work with formhandler 2.1 and TYPO3 7.6 LTS.

Please check it out and let me know if you experience any problems.

Cheers,
Alex

**Comment by arunc43** [comment]
Hi Alex,

Thank you very much for fixing the issues. Its working perfectly!!
May be you can publish this extension to the Typo3 repository...:)

One minor thing I noticed is that if we select the redirect page in the flexform of the plugin,
it shows an error like this;

> finishers fehlt! Flexform beinhaltet '44',aber die TypoScript-Konfiguration ist unvollständig. Bitte fügen Sie '\Typoheads\Formhandler\Finisher\Redirect' hinzu! 

But if we add redirect page in typoscript, it is working normally.

Thanks,
Arun

**Comment by astehlik** [comment]
Hi Arun,

I released a new version to TER yesterday.

Since I had some trouble during upload there are now three new versions which are basically identical, sorry for that :(

The lastest release is 1.0.3 which contains the TYPO3 7.6 / formhandler 2.1 fixes.

Cheers,
Alex

**Comment by astehlik** [comment]
Sorry, totally overread you error report about the TypoScript config, will look into that.

Thanks for testing and your feedback!

**Comment by astehlik** [comment]
OK, I figured it out. This is a formhandler issue that is fixed in current master:

https://forge.typo3.org/issues/73360
https://github.com/boristimp/formhandler/commit/6e87cebbc6be5ab56f267d07936a13b2e9245bcc
